---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  


    - name: "deploy codecov checkstyle maven(single pom) on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      cache:
        directories:
        - ~/.m2
      before_install:
        - java -version
      script:
        - cd maven-checkstyle
        - mvn checkstyle:checkstyle
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate


    - name: "deploy codecov cobertura junit4 maven(single pom) on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - cd codecov-test2
        - mvn clean package
        - mvn cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate


    - name: "deploy codecov cobertura junit4 maven(parent-child pom) on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - mvn clean package
        - mvn cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate

  
    - name: "build ruby w mocha rubocop webmock codecov on bionic arm64"
      os: linux 
      dist: bionic
      arch: amd64
      sudo: false         
      language: ruby
      rvm:
        - 2.5
        - 2.6
        - 2.7
        - jruby
        - jruby-9.2
      before_install:
        - cd ruby-pipeline/app1
      script:
        - bundle exec rake
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate

   
# https://github.com/simplecov-ruby/simplecov  SimpleCov code coverage analysis tool   
# https://rspec.info/ RSpec BDD test framework
# https://www.ruby-lang.org/en/    
    - name: "build ruby w simplecov rspec on bionic arm64"
      os: linux 
      dist: bionic
      arch: amd64
      sudo: false         
      language: ruby
      rvm:
        - 2.5
        - 2.6
        - 2.7
        - jruby
        - jruby-9.2
      before_install:
        - cd ruby-pipeline/app2
      script:
        - bundle install
        - bundle exec rspec
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate
