---
sudo: required
notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:  

    - name: "deploy codecov checkstyle maven(single pom) on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      cache:
        directories:
        - ~/.m2
      before_install:
        - java -version
      script:
        - cd maven-checkstyle
        - mvn checkstyle:checkstyle
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate

    - name: "deploy codecov cobertura junit4 maven(single pom) on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - cd codecov-test2
        - mvn clean package
        - mvn cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate

    - name: "deploy codecov cobertura junit4 maven(parent-child pom) on bionic arm64"
      dist: bionic
      arch: amd64         
      language: java
      jdk:
      - openjdk8
      before_install:
        - java -version
      script:
        - mvn clean package
        - mvn cobertura:cobertura
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - deactivate
