
name: "macos Building Java Applications CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  Groovy-win-latest-gradle-script:
    name: "Building Java Applications Sample Groovy"
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Groovy"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl groovy
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework spock
          # gradle init --project-name demo --type java-application --dsl groovy --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run
          echo "==================Bundle the application=================================================================="              
          ./gradlew build           
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle
         

  Kotlin-win-latest-gradle-script:
    name: "Building Java Applications Sample Kotlin"
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "Building Java Applications Sample Kotlin"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl kotlin
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework junit-jupiter
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework spock
          # gradle init --project-name demo --type java-application --dsl kotlin --test-framework testng
          echo "==================Run the application=================================================================="   
          ./gradlew run        
          echo "==================Bundle the application=================================================================="              
          ./gradlew build 
          echo "==================Publish a Build Scan=================================================================="              
          ./gradlew build --scan
          cat app/build.gradle.kts          
