
name: "ubuntu codecov-pipeline CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  ubuntu-latest-gradle-findbugs-codecov:
    name: "build gradle w findbugs codecov"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "build gradle w findbugs codecov on - Debian GNU/Linux 10 (buster) x86_64"
      run: |
            echo "=============================build gradle w findbugs codecov============================================================="
            java -version
            gradle -v
            cd gradle-pipeline && chmod +x gradlew
            ./gradlew jacocoTestReport
            echo "=============================build gradle w findbugs codecov============================================================="
    - name: "upload codecov"
      run: bash <(curl -s https://codecov.io/bash)


  ubuntu-latest-gradle-script:
    name: "build gradle scripts"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    - name: "holamundo task groovy"
      run: |
          cd app1 && gradle -q holamundo    
    - name: "holamundo task kotlin"
      run: |
          cd app1 && gradle -q holamundo   
    # https://docs.gradle.org/current/userguide/tutorial_using_tasks.html          
    - name: "Build scripts are code groovy"
      run: |
          cd app2 && gradle -q upper    
    - name: "Build scripts are code kotlin"
      run: |
          cd app2 && gradle -q upper     
    # https://docs.gradle.org/current/userguide/tutorial_using_tasks.html          
    - name: "Default tasks groovy"
      run: |
          cd app3 && gradle -q  
    - name: "Default tasks kotlin"
      run: |
          cd app3 && gradle -q
    - name: "Gradle sample"
      run: |
          cd app4 && gradle tasks         