
name: "ubuntu Testing Build Logic with TestKit CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  ubuntu-latest-gradle-script:
    name: "build gradle scripts"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "osfingerprinting"
      run: |
        echo "===================================================================================="
                                  hostnamectl status
        echo "===================================================================================="
        echo "         \   ^__^                                                                  "
        echo "          \  (oo)\_______                                                          "
        echo "             (__)\       )\/\                                                      "
        echo "                 ||----w |                                                         "
        echo "                 ||     ||                                                         "
        echo "===================================================================================="   
    # https://docs.gradle.org/current/userguide/test_kit.html
    # - name: "use the TestKit"
    #   run: |
    #       cd app5 && gradle -q
    # - name: "Declaring the JUnit dependency"
    #   run: |
    #       cd app6 && gradle -q            
    # https://docs.gradle.org/current/samples/index.html 
    # https://docs.gradle.org/current/samples/sample_building_java_applications.html
    # https://docs.gradle.org/current/userguide/build_init_plugin.html
    # https://docs.gradle.org/current/samples/sample_building_java_applications.html
    - name: "Building Java Applications Sample Groovy"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl Groovy
          ./gradlew run
    - name: "Building Java Applications Sample Kotlin"
      run: |
          mkdir demo && cd demo
          gradle init --project-name demo --type java-application --dsl Kotlin
          ./gradlew run          
