
name: "windows codecov-pipeline CI workflow"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month

jobs:

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "build gradle w findbugs codecov"
      run: |
            echo "=============================build gradle w findbugs codecov============================================================="
            java -version
            gradle -v
    - name: "holamundo task groovy"
      run: |
          cd app1 && gradle -q holamundo    
    - name: "holamundo task kotlin"
      run: |
          cd app1 && gradle -q holamundo    
    # https://docs.gradle.org/current/userguide/tutorial_using_tasks.html          
    - name: "Build scripts are code groovy"
      run: |
          cd app2 && gradle -q upper    
    - name: "Build scripts are code kotlin"
      run: |
          cd app2 && gradle -q upper                       

